spring:
  application:
    name: infrastructure
  datasource:
     url: jdbc:mysql://localhost:3306/bookvoyage_db
     username: root
     password: your_mysql_password
     driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        # For MySQL, uncomment and configure below:
        # dialect: org.hibernate.dialect.MySQL8Dialect